### ISSUE TITLE
DeviceSettings: Introducing Doze menu 

### ISSUE THREAD

**Issue by Codecity001** [dotOS-Devices/android_device_oneplus_sm8150-common#1]
**Adding Doze menu to support** 

1. Pulse notifications on pick-up
2. Wake device on pick-up

**Commits/References to Implement Doze menu:**

1. https://github.com/Codecity001/android_device_oneplus_sm8150-common/commit/1f397c0e811ad1ebf0597e67c45824a2a7f45f6c
2. https://github.com/Codecity001/android_device_oneplus_sm8150-common/commit/a1e0d884fb309d4ea55375383684f83b5499a4b0

**Preview**
![image](https://user-images.githubusercontent.com/60321588/129444056-dd4768f7-6077-4d0c-9c46-453b5bc2f181.png)

**Comment by matt0301** [comment]
Merged! Thks!
