### ISSUE TITLE
DeviceSettings: Introducing FPS Overlay

### ISSUE THREAD

**Issue by Codecity001** [dotOS-Devices/android_device_oneplus_sm8150-common#2]
Adding FPS overlay to display current FPS meter on screen using toggle from DeviceSettings and QuickSetting Tile 

Commits/References to Implement FPS Overlay:

- https://github.com/Codecity001/android_device_oneplus_sm8150-common/commit/4b5457d935020a84490793c9347730b677ba0262

**Preview**
![image](https://user-images.githubusercontent.com/60321588/129444136-838500b5-5875-475b-b951-925a52db5760.png)
![image](https://user-images.githubusercontent.com/60321588/129444222-9a89fe84-f586-4e43-866d-17291492be5b.png)

**Comment by matt0301** [comment]
Nice, will merge it today, thks for the tip!
